# -*- coding: utf-8 -*-
"""C120 Project solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a6yfn8-SbuO_Q3PgZa_ZH_1KOK1s1hDm

Loading a already present data set in the  scikit-learn library.
"""

#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
wine = datasets.load_wine()

"""Exploring the data"""

# print the names of the 13 features
print("Features: ", wine.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", wine.target_names)

"""Spliting the data."""

#Import train_test_split
from sklearn.model_selection import train_test_split

X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=109) #70% training and 30% test

"""# Train the model with Naive Bayes and print the accuracy"""

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)

"""Evaluating the model to check it's accuracy"""

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))